name: "Frontend Deploy"
description: "Deploy artifact to an environment"
inputs:
  artifact-number:
    description: "build artifact to fetch"
    default: latest
  artifact-bucket:
    description: "where to fetch artifact from"
    required: true
  artifact-prefix:
    description: "the prefix the artifact is resides in"
    default: ""
  environment-bucket:
    description: "where to deploy the artifact"
    required: true
  app-prefix:
    description: "which prefix to deploy to"
    default: ""
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/cleanup.js'
